"""Native operation blocks extracted without changing tensor expressions.

Generated by scripts/bootstrap_m0.py from the pinned reference. Source expressions
remain reviewable here; no runtime code generation or patching of reference modules.
"""
import math
import torch
import torch.nn.functional as F
from .runtime import activate_reference
activate_reference()
from ergt_reviewer.physics_core import PhysicsNativeSubstrate, ERGT42Error, _sinusoidal_positions
from ergt_reviewer.native_solver import (
    NativeGeometricBoundaryModel, INTERVENTIONS, ERGT43Error,
    padding_independent_multiscale_support, _selected_event_fields,
    event_graph_spectral_observer, soft_min_plus_typed_boundary_solve,
)


class SteppedSubstrate(PhysicsNativeSubstrate):
    def seed_native_state(self, token_ids, attention_mask, *, identity_fibre=None):
        if token_ids.dim() != 2 or attention_mask.shape != token_ids.shape:
            raise ERGT42Error("token_ids and attention_mask must have matching [B, T] shape")
        if token_ids.size(1) > self.config.max_tokens:
            raise ERGT42Error("input exceeds configured positional capacity")
        position = _sinusoidal_positions(
            token_ids.size(1), self.config.hidden_dim, token_ids.device
        )
        token_seed = self.token_embedding(token_ids)
        # Identity is an initial-condition charge: geometry may move and update
        # payload state, but repeated symbols must remain bindable after transport.
        if identity_fibre is None:
            identity = self.identity_seed(token_seed)
            identity_initial_condition = torch.zeros_like(token_seed)
        else:
            if identity_fibre.dim() != 3 or identity_fibre.shape[:2] != token_ids.shape:
                raise ERGT42Error("identity_fibre must have shape [B, T, D]")
            if identity_fibre.size(-1) != self.config.identity_fibre_dim:
                raise ERGT42Error(
                    "identity_fibre width does not match configured conserved charge"
                )
            identity = identity_fibre.to(device=token_ids.device, dtype=token_seed.dtype)
            identity_initial_condition = self.external_identity_seed(identity)
        identity = F.normalize(identity, dim=-1, eps=self.config.eps)
        identity = identity * attention_mask.unsqueeze(-1).to(identity.dtype)
        identity_gain = 0.75 + 0.50 * torch.sigmoid(self.identity_initial_condition_gain_raw)
        identity_initial_condition = identity_initial_condition * attention_mask.unsqueeze(-1).to(
            token_seed.dtype
        )
        normalized_condition = F.normalize(
            identity_initial_condition, dim=-1, eps=self.config.eps
        )
        condition_distance = (
            normalized_condition[:, :, None, :] - normalized_condition[:, None, :, :]
        ).square().sum(dim=-1)
        exact_identity_distance = (
            identity[:, :, None, :] - identity[:, None, :, :]
        ).square().sum(dim=-1)
        valid_pair = attention_mask[:, :, None] & attention_mask[:, None, :]
        distinct_identity = valid_pair & (exact_identity_distance > 1.0e-5)
        distinct_count = distinct_identity.sum().clamp_min(1)
        identity_condition_collision_rate = (
            distinct_identity & (condition_distance <= 1.0e-6)
        ).sum().to(token_seed.dtype) / distinct_count.to(token_seed.dtype)
        identity_condition_min_separation = condition_distance.masked_fill(
            ~distinct_identity, float("inf")
        ).amin()
        identity_condition_min_separation = torch.where(
            distinct_identity.any(),
            identity_condition_min_separation,
            condition_distance.new_tensor(0.0),
        )
        psi = self.psi_seed(
            token_seed + position.unsqueeze(0) + identity_gain * identity_initial_condition
        )
        psi = psi * attention_mask.unsqueeze(-1).to(psi.dtype)
        # Operator identity is an internal charge of the initial Psi state. It
        # may be carried to geometric endpoints, but the evolving metric must
        # not transmute plus_one, plus_two, or hold into one another.
        typed_payload_charge = F.normalize(psi, dim=-1, eps=self.config.eps)
        typed_payload_charge = typed_payload_charge * attention_mask.unsqueeze(-1).to(psi.dtype)
        momentum = torch.zeros_like(psi)
        edge_memory: torch.Tensor | None = None
        bulk_deficit = torch.zeros_like(token_ids, dtype=psi.dtype)
        bulk_losses: list[torch.Tensor] = []
        final: dict[str, torch.Tensor] = {}


        return {"token_ids": token_ids, "attention_mask": attention_mask, "identity": identity, "token_seed": token_seed, "identity_initial_condition": identity_initial_condition, "identity_gain": identity_gain, "identity_condition_collision_rate": identity_condition_collision_rate, "identity_condition_min_separation": identity_condition_min_separation, "typed_payload_charge": typed_payload_charge, "psi": psi, "momentum": momentum, "edge_memory": edge_memory, "bulk_deficit": bulk_deficit, "bulk_losses": bulk_losses, "final": final}

    def observe_native_state(self, state, *, intervention="full"):
        token_ids = state["token_ids"]
        attention_mask = state["attention_mask"]
        identity = state["identity"]
        token_seed = state["token_seed"]
        identity_initial_condition = state["identity_initial_condition"]
        identity_gain = state["identity_gain"]
        identity_condition_collision_rate = state["identity_condition_collision_rate"]
        identity_condition_min_separation = state["identity_condition_min_separation"]
        typed_payload_charge = state["typed_payload_charge"]
        psi = state["psi"]
        momentum = state["momentum"]
        edge_memory = state["edge_memory"]
        bulk_deficit = state["bulk_deficit"]
        bulk_losses = state["bulk_losses"]
        final = state["final"]
        obs = self._pair_observables(psi, identity, attention_mask, bulk_deficit)
        phi = self._phi_gate(obs)
        if intervention == "no_phi":
            phi = torch.ones_like(phi)
        potential = self._world_potentials(obs)

        return {"obs": obs, "phi": phi, "potential": potential}

    def preview_native_geometry(self, state, observations, *, intervention="full", intervention_seed=0):
        token_ids = state["token_ids"]
        attention_mask = state["attention_mask"]
        identity = state["identity"]
        token_seed = state["token_seed"]
        identity_initial_condition = state["identity_initial_condition"]
        identity_gain = state["identity_gain"]
        identity_condition_collision_rate = state["identity_condition_collision_rate"]
        identity_condition_min_separation = state["identity_condition_min_separation"]
        typed_payload_charge = state["typed_payload_charge"]
        psi = state["psi"]
        momentum = state["momentum"]
        edge_memory = state["edge_memory"]
        bulk_deficit = state["bulk_deficit"]
        bulk_losses = state["bulk_losses"]
        final = state["final"]
        obs, phi, potential = (observations[k] for k in ("obs", "phi", "potential"))
        candidate_weight = potential * phi.unsqueeze(1)
        if edge_memory is None or intervention == "no_memory_geometry":
            edge_memory = candidate_weight
        else:
            rate = self.config.edge_memory_rate
            edge_memory = rate * edge_memory + (1.0 - rate) * candidate_weight
        edge_memory = edge_memory * obs["off_diagonal"][:, None].to(psi.dtype)
        edge_memory, active_worlds = self._intervene(
            edge_memory,
            intervention=intervention,
            seed=intervention_seed,
        )
        sparse_gate = self._sparse_mask(edge_memory, obs["off_diagonal"])
        sparse_weight = edge_memory * sparse_gate
        edge_length = -torch.log(edge_memory.clamp_min(self.config.eps))
        edge_length = edge_length.masked_fill(~obs["off_diagonal"][:, None], 30.0)

        velocity = self.config.cone_velocity_floor + 2.0 * torch.sigmoid(
            self.velocity_head(psi).squeeze(-1)
        )
        positions = torch.arange(token_ids.size(1), device=psi.device)
        separation = (positions[:, None] - positions[None, :]).abs().to(psi.dtype)
        # Proper time is an intrinsic per-example quantity.  Normalizing
        # by the padded tensor width made cone budgets depend on how an
        # otherwise identical example happened to be batched at audit
        # time.  The valid-token extent removes that external gauge.
        valid_extent = (
            attention_mask.sum(dim=1).sub(1).clamp_min(1).to(psi.dtype).view(-1, 1, 1)
        )
        proper_time = 1.0 + separation.unsqueeze(0) / valid_extent
        cone_budget = velocity[:, None, :, None] * proper_time[:, None]
        cone = edge_length <= cone_budget
        admissible = (sparse_gate.detach() > 0.5) & cone & obs["off_diagonal"][:, None]
        action = (
            edge_length
            + 0.75 * (1.0 - obs["boundary_reconstructibility"][:, None])
            + 0.50 * (1.0 - obs["stability"][:, None])
            + (~cone).to(psi.dtype) * 8.0
        )

        diagonal = torch.eye(token_ids.size(1), dtype=torch.bool, device=psi.device).view(
            1, 1, token_ids.size(1), token_ids.size(1)
        )
        identity_transport = diagonal & attention_mask[:, None, :, None]
        transport_mask = admissible | identity_transport
        transport_logits = -action / self.config.transport_temperature
        transport_logits = transport_logits.masked_fill(~transport_mask, -1.0e4)
        transport = torch.softmax(transport_logits, dim=-1)
        program_admissible = admissible
        if intervention == "no_transport":
            transport = identity_transport.to(psi.dtype).expand(
                token_ids.size(0), self.config.n_worlds, -1, -1
            )
            program_admissible = torch.zeros_like(admissible)

        return {"obs": obs, "phi": phi, "potential": potential, "edge_memory": edge_memory, "active_worlds": active_worlds, "sparse_gate": sparse_gate, "sparse_weight": sparse_weight, "edge_length": edge_length, "cone": cone, "cone_budget": cone_budget, "action": action, "transport": transport, "program_admissible": program_admissible}

    def advance_native_field(self, state, geometry, *, intervention="full"):
        token_ids = state["token_ids"]
        attention_mask = state["attention_mask"]
        identity = state["identity"]
        token_seed = state["token_seed"]
        identity_initial_condition = state["identity_initial_condition"]
        identity_gain = state["identity_gain"]
        identity_condition_collision_rate = state["identity_condition_collision_rate"]
        identity_condition_min_separation = state["identity_condition_min_separation"]
        typed_payload_charge = state["typed_payload_charge"]
        psi = state["psi"]
        momentum = state["momentum"]
        edge_memory = state["edge_memory"]
        bulk_deficit = state["bulk_deficit"]
        bulk_losses = state["bulk_losses"]
        final = state["final"]
        obs = geometry["obs"]
        phi = geometry["phi"]
        potential = geometry["potential"]
        edge_memory = geometry["edge_memory"]
        active_worlds = geometry["active_worlds"]
        sparse_gate = geometry["sparse_gate"]
        sparse_weight = geometry["sparse_weight"]
        edge_length = geometry["edge_length"]
        cone = geometry["cone"]
        cone_budget = geometry["cone_budget"]
        action = geometry["action"]
        transport = geometry["transport"]
        program_admissible = geometry["program_admissible"]
        bulk_losses = list(bulk_losses)
        transported_worlds = torch.stack(
            [
                torch.bmm(transport[:, world], self.world_value[world](psi))
                for world in range(self.config.n_worlds)
            ],
            dim=1,
        )
        active_count = active_worlds.sum().clamp_min(1).to(psi.dtype)
        message = (transported_worlds * active_worlds.view(1, -1, 1, 1).to(psi.dtype)).sum(
            dim=1
        ) / active_count
        force = self.field_update(torch.cat((psi, message), dim=-1))
        momentum = (
            self.config.field_momentum * momentum + (1.0 - self.config.field_momentum) * force
        )
        psi = self.field_norm(psi + momentum)
        psi = psi * attention_mask.unsqueeze(-1).to(psi.dtype)
        bulk_deficit, bulk_loss = self._bulk_boundary_deficit(psi, transport, attention_mask)
        bulk_losses.append(bulk_loss)
        final = {
            "psi": psi,
            "semantic_token_seed": token_seed,
            "identity": identity,
            "identity_initial_condition": identity_initial_condition,
            "identity_initial_condition_gain": identity_gain,
            "identity_initial_condition_collision_rate": (
                identity_condition_collision_rate
            ),
            "identity_initial_condition_min_separation": (
                identity_condition_min_separation
            ),
            "typed_payload_charge": typed_payload_charge,
            "phi": phi,
            "world_potential": potential,
            "world_edge_weight": edge_memory,
            "world_sparse_weight": sparse_weight,
            "world_edge_length": edge_length,
            "world_action": action,
            "world_cone": cone.to(psi.dtype),
            "world_cone_budget": cone_budget,
            "world_program_mask": program_admissible,
            "world_transport": transport,
            "transported_worlds": transported_worlds,
            "active_worlds": active_worlds,
            "bulk_boundary_deficit": bulk_deficit,
            "bulk_boundary_loss": torch.stack(bulk_losses).mean(),
            "density": obs["density"],
            "coherence": obs["coherence"],
            "stability": obs["stability"],
            "reconstructibility": obs["boundary_reconstructibility"],
            "identity_overlap": obs["identity_overlap"],
            "identity_distance": obs["identity_distance"],
            "program_transport_enabled": psi.new_tensor(float(intervention != "no_transport")),
            "event_backreaction_enabled": psi.new_tensor(
                float(intervention != "no_event_backreaction")
            ),
        }


        return {"token_ids": token_ids, "attention_mask": attention_mask, "identity": identity, "token_seed": token_seed, "identity_initial_condition": identity_initial_condition, "identity_gain": identity_gain, "identity_condition_collision_rate": identity_condition_collision_rate, "identity_condition_min_separation": identity_condition_min_separation, "typed_payload_charge": typed_payload_charge, "psi": psi, "momentum": momentum, "edge_memory": edge_memory, "bulk_deficit": bulk_deficit, "bulk_losses": bulk_losses, "final": final}

    def finalize_native_snapshot(self, state, *, observe_spectrum=False):
        token_ids = state["token_ids"]
        attention_mask = state["attention_mask"]
        identity = state["identity"]
        token_seed = state["token_seed"]
        identity_initial_condition = state["identity_initial_condition"]
        identity_gain = state["identity_gain"]
        identity_condition_collision_rate = state["identity_condition_collision_rate"]
        identity_condition_min_separation = state["identity_condition_min_separation"]
        typed_payload_charge = state["typed_payload_charge"]
        psi = state["psi"]
        momentum = state["momentum"]
        edge_memory = state["edge_memory"]
        bulk_deficit = state["bulk_deficit"]
        bulk_losses = state["bulk_losses"]
        final = state["final"]
        final = dict(final)
        valid_edges = final["world_program_mask"].to(psi.dtype)
        edge_mass = (final["world_edge_weight"] * valid_edges).sum(dim=(-1, -2))
        edge_mass = edge_mass / valid_edges.sum(dim=(-1, -2)).clamp_min(1.0)
        usage = edge_mass.mean(dim=0)
        usage_probability = usage / usage.sum().clamp_min(self.config.eps)
        final["world_usage"] = usage_probability
        final["world_usage_entropy"] = -(
            usage_probability.clamp_min(self.config.eps)
            * usage_probability.clamp_min(self.config.eps).log()
        ).sum() / math.log(float(self.config.n_worlds))
        flattened = F.normalize(
            final["world_edge_weight"].flatten(start_dim=2), dim=-1, eps=self.config.eps
        )
        cosine = torch.einsum("bwd,bvd->bwv", flattened, flattened)
        triangle = torch.triu(
            torch.ones(
                self.config.n_worlds,
                self.config.n_worlds,
                dtype=torch.bool,
                device=psi.device,
            ),
            diagonal=1,
        )
        final["world_geometry_diversity"] = (1.0 - cosine[:, triangle].mean()).clamp(0.0, 1.0)
        # Curvature is a frozen observer.  Detaching here guarantees that it
        # cannot become a hidden training path even if downstream reporting
        # retains the returned tensors.
        with torch.no_grad():
            final.update(
                self.curvature_observer(
                    final["world_sparse_weight"].detach(),
                    attention_mask,
                )
            )
        if observe_spectrum:
            final.update(self.spectral_observer(final["world_edge_weight"], attention_mask))
        else:
            zero = psi.new_tensor(0.0)
            final.update(
                {
                    "spectral_entropy": zero,
                    "spectral_effective_rank": zero,
                    "spectral_gap": zero,
                    "spectral_world_diversity": zero,
                }
            )
        return final

    def forward(self, token_ids, attention_mask, *, identity_fibre=None, intervention="full", intervention_seed=0, observe_spectrum=False, trace=None):
        state = self.seed_native_state(token_ids, attention_mask, identity_fibre=identity_fibre)
        if trace is not None:
            trace.append({"psi": state["psi"].detach().clone(), "typed_payload_charge": state["typed_payload_charge"].detach().clone()})
        for _ in range(self.config.field_steps):
            observations = self.observe_native_state(state, intervention=intervention)
            geometry = self.preview_native_geometry(state, observations, intervention=intervention, intervention_seed=intervention_seed)
            state = self.advance_native_field(state, geometry, intervention=intervention)
            if trace is not None:
                trace.append({k: v.detach().clone() for k, v in state["final"].items() if isinstance(v, torch.Tensor)})
        return self.finalize_native_snapshot(state, observe_spectrum=observe_spectrum)


class SteppedNative(NativeGeometricBoundaryModel):
    def __init__(self, config):
        super().__init__(config)
        self.substrate.__class__ = SteppedSubstrate

    def probe_native_proposals(self, state, attention_mask):
        induced = self.field_inducer(state, attention_mask)
        induced["relation_authorized_worlds"] = self.field_inducer.role_world_contract[1]
        induced = padding_independent_multiscale_support(
            state,
            induced,
            attention_mask,
            self.config,
        )
        induced = {
            **induced,
            **self.identity_binder(state, induced, attention_mask),
        }

        return induced

    def finish_native_execution(self, state, induced, token_ids, attention_mask, *, intervention="full", observe_spectrum=False):
        physical = self.physical_conditions(state["psi"], attention_mask)
        outputs = {**state, **induced, **physical}
        outputs["internal_semantic_token_ids"] = token_ids
        outputs["attention_mask"] = attention_mask
        outputs["relation_authorized_worlds"] = self.field_inducer.role_world_contract[1]
        outputs["base_world_usage_entropy"] = state["world_usage_entropy"]
        outputs["base_world_geometry_diversity"] = state["world_geometry_diversity"]
        outputs["world_usage_entropy"] = induced["program_world_usage_entropy"]
        outputs["world_geometry_diversity"] = induced["program_world_geometry_diversity"]
        selected = _selected_event_fields(outputs, self.config, intervention=intervention)
        outputs.update(selected)
        if observe_spectrum:
            outputs.update(
                event_graph_spectral_observer(
                    outputs,
                    outputs["selected_event_indices"],
                    outputs["event_presence"],
                    event_presence_floor=self.config.event_presence_floor,
                    eps=self.config.eps,
                )
            )
        else:
            zero = outputs["event_presence"].new_zeros(outputs["event_presence"].size(0))
            outputs.update(
                {
                    "event_spectral_entropy": zero,
                    "event_spectral_effective_rank": zero,
                    "event_spectral_gap": zero,
                    "event_spectral_world_diversity": zero,
                }
            )
        logits, candidate_cost = soft_min_plus_typed_boundary_solve(
            outputs,
            max_hops=self.config.max_hops,
            temperature=self.config.softmin_temperature,
            transmission_floor=self.config.transmission_floor,
            boundary_deficit_ceiling=self.config.boundary_deficit_ceiling,
            terminal_mass_floor=self.config.terminal_mass_floor,
            eps=self.config.eps,
        )
        outputs["native_answer_logits"] = logits
        outputs["candidate_soft_action"] = candidate_cost
        outputs["architecture_attention_free"] = logits.new_tensor(1.0)
        outputs["old_discrete_compiler_disabled"] = logits.new_tensor(1.0)
        outputs["old_generic_executor_disabled"] = logits.new_tensor(1.0)
        outputs["typed_conservation_residual"] = (
            (outputs["event_relation_probability"].sum(dim=-1) - outputs["event_presence"])
            .abs()
            .max()
        )
        valid_transport = attention_mask[:, None, :].to(outputs["world_transport"].dtype)
        outputs["payload_conservation_residual"] = (
            (outputs["world_transport"].sum(dim=-1) - 1.0).abs() * valid_transport
        ).max()
        return outputs

    def _forward_from_internal_state(self, token_ids, attention_mask, *, identity_fibre, intervention, intervention_seed, observe_spectrum):
        if intervention not in INTERVENTIONS:
            raise ERGT43Error(f"unregistered intervention: {intervention}")
        state = self.substrate(token_ids, attention_mask, identity_fibre=identity_fibre,
            intervention=self._substrate_intervention(intervention), intervention_seed=intervention_seed,
            observe_spectrum=False)
        induced = self.probe_native_proposals(state, attention_mask)
        return self.finish_native_execution(state, induced, token_ids, attention_mask,
            intervention=intervention, observe_spectrum=observe_spectrum)

