"""Create a byte-identical reference and a mechanical, reviewable step extraction."""
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from ergt_phi.research_paths import workspace_path
import hashlib
import json
import shutil
import textwrap

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / "ERGT-paper-main"
REFERENCE = ROOT / "reference"


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def create_reference():
    for directory in ("configs", "docs", "ergt_phi", "tests", "runs"):
        (ROOT / directory).mkdir(exist_ok=True)
    records = {}
    for row in (SOURCE / "MANIFEST.sha256").read_text().splitlines():
        if not row.strip():
            continue
        expected, relative = row.split("  ", 1)
        source = SOURCE / relative
        if digest(source) != expected:
            raise RuntimeError(f"Original source mismatch: {relative}")
        target = REFERENCE / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists() and digest(target) != expected:
            raise RuntimeError(f"Refusing to overwrite altered reference: {relative}")
        if not target.exists():
            shutil.copyfile(source, target)
        records[relative] = expected
    shutil.copyfile(SOURCE / "MANIFEST.sha256", REFERENCE / "MANIFEST.sha256")
    records["MANIFEST.sha256"] = digest(REFERENCE / "MANIFEST.sha256")
    (workspace_path(ROOT, "manifests/reference.json")).write_text(json.dumps({
        "original_root": str(SOURCE), "files": records,
        "reference_policy": "byte-identical; no reference edits",
    }, indent=2), encoding="utf-8")
    shutil.copyfile(ROOT.parent / "MATHEMATICAL_SPEC (1).md", ROOT / "docs/MATHEMATICAL_SPEC.md")


def method(name, arguments, body):
    return f"    def {name}({arguments}):\n" + textwrap.indent(textwrap.dedent(body).strip() + "\n", "        ") + "\n"


def extract_steps():
    runtime = REFERENCE / "ergt_four_seed/_locked_runtime/ergt_reviewer"
    physics = (runtime / "physics_core.py").read_text(encoding="utf-8")
    native = (runtime / "native_solver.py").read_text(encoding="utf-8")
    body = physics.split("    def forward(\n", 1)[1]
    body = body[body.index("        if token_ids.dim()"):]
    seed, rest = body.split("        for _ in range(self.config.field_steps):\n", 1)
    loop, tail = rest.split('        valid_edges = final["world_program_mask"]', 1)
    tail = '        valid_edges = final["world_program_mask"]' + tail.split("\nclass RolePreservingGeometricFieldInducer", 1)[0]
    observe, rest = loop.split("            candidate_weight =", 1)
    geometry, advance = ("            candidate_weight =" + rest).split("            transported_worlds =", 1)
    advance = "            transported_worlds =" + advance
    seed_keys = "token_ids attention_mask identity token_seed identity_initial_condition identity_gain identity_condition_collision_rate identity_condition_min_separation typed_payload_charge psi momentum edge_memory bulk_deficit bulk_losses final".split()
    geometry_keys = "obs phi potential edge_memory active_worlds sparse_gate sparse_weight edge_length cone cone_budget action transport program_admissible".split()
    unpack_seed = "\n".join(f'{key} = state["{key}"]' for key in seed_keys)
    unpack_geometry = "\n".join(f'{key} = geometry["{key}"]' for key in geometry_keys)
    pack = lambda keys: "{" + ", ".join(f'"{key}": {key}' for key in keys) + "}"
    output = '''"""Native operation blocks extracted without changing tensor expressions.

Generated by scripts/bootstrap_m0.py from the pinned reference. Source expressions
remain reviewable here; no runtime code generation or patching of reference modules.
"""
import math
import torch
import torch.nn.functional as F
from .runtime import activate_reference
activate_reference()
from ergt_reviewer.physics_core import PhysicsNativeSubstrate, ERGT42Error, _sinusoidal_positions
from ergt_reviewer.native_solver import (
    NativeGeometricBoundaryModel, INTERVENTIONS, ERGT43Error,
    padding_independent_multiscale_support, _selected_event_fields,
    event_graph_spectral_observer, soft_min_plus_typed_boundary_solve,
)


class SteppedSubstrate(PhysicsNativeSubstrate):
'''
    output += method("seed_native_state", "self, token_ids, attention_mask, *, identity_fibre=None", textwrap.dedent(seed) + "\nreturn " + pack(seed_keys))
    output += method("observe_native_state", 'self, state, *, intervention="full"', unpack_seed + "\n" + textwrap.dedent(observe) + '\nreturn {"obs": obs, "phi": phi, "potential": potential}')
    output += method("preview_native_geometry", 'self, state, observations, *, intervention="full", intervention_seed=0', unpack_seed + '\nobs, phi, potential = (observations[k] for k in ("obs", "phi", "potential"))\n' + textwrap.dedent(geometry) + "\nreturn " + pack(geometry_keys))
    output += method("advance_native_field", 'self, state, geometry, *, intervention="full"', unpack_seed + "\n" + unpack_geometry + "\nbulk_losses = list(bulk_losses)\n" + textwrap.dedent(advance) + "\nreturn " + pack(seed_keys))
    output += method("finalize_native_snapshot", "self, state, *, observe_spectrum=False", unpack_seed + "\nfinal = dict(final)\n" + textwrap.dedent(tail))
    output += method("forward", 'self, token_ids, attention_mask, *, identity_fibre=None, intervention="full", intervention_seed=0, observe_spectrum=False, trace=None', '''
state = self.seed_native_state(token_ids, attention_mask, identity_fibre=identity_fibre)
if trace is not None:
    trace.append({"psi": state["psi"].detach().clone(), "typed_payload_charge": state["typed_payload_charge"].detach().clone()})
for _ in range(self.config.field_steps):
    observations = self.observe_native_state(state, intervention=intervention)
    geometry = self.preview_native_geometry(state, observations, intervention=intervention, intervention_seed=intervention_seed)
    state = self.advance_native_field(state, geometry, intervention=intervention)
    if trace is not None:
        trace.append({k: v.detach().clone() for k, v in state["final"].items() if isinstance(v, torch.Tensor)})
return self.finalize_native_snapshot(state, observe_spectrum=observe_spectrum)
''')
    function = native.split("    def _forward_from_internal_state(\n", 1)[1].split("    def _forward_impl(\n", 1)[0]
    probe = "        induced = self.field_inducer" + function.split("        induced = self.field_inducer", 1)[1].split("        physical =", 1)[0]
    finish = "        physical =" + function.split("        physical =", 1)[1]
    output += '\nclass SteppedNative(NativeGeometricBoundaryModel):\n'
    output += method("__init__", "self, config", "super().__init__(config)\nself.substrate.__class__ = SteppedSubstrate")
    output += method("probe_native_proposals", "self, state, attention_mask", textwrap.dedent(probe) + "\nreturn induced")
    output += method("finish_native_execution", 'self, state, induced, token_ids, attention_mask, *, intervention="full", observe_spectrum=False', textwrap.dedent(finish))
    output += method("_forward_from_internal_state", 'self, token_ids, attention_mask, *, identity_fibre, intervention, intervention_seed, observe_spectrum', '''
if intervention not in INTERVENTIONS:
    raise ERGT43Error(f"unregistered intervention: {intervention}")
state = self.substrate(token_ids, attention_mask, identity_fibre=identity_fibre,
    intervention=self._substrate_intervention(intervention), intervention_seed=intervention_seed,
    observe_spectrum=False)
induced = self.probe_native_proposals(state, attention_mask)
return self.finish_native_execution(state, induced, token_ids, attention_mask,
    intervention=intervention, observe_spectrum=observe_spectrum)
''')
    (ROOT / "ergt_phi/native_steps.py").write_text(output, encoding="utf-8")
    compile(output, "native_steps.py", "exec")


if __name__ == "__main__":
    create_reference()
    extract_steps()
    print("Reference copied and native step extraction generated.")
